Task 1
CC-BHU/web-development pull request #18
Opened 2023-04-24 09:54 UTC by VarshaSaroj

2023-04-24 10:18 UTC, saurabhanilpandey approved these changes
Congratulations on completing task 1

2023-04-24 14:23 UTC, PradyumnaKrishna requested changes
I am sorry but the folder name is still incorrect. It should be `VarshaSaroj` instead of `Varsha2001`.

Please fix this as I won't be able to merge this with incorrect folder name.

2023-04-24 14:23 UTC, PradyumnaKrishna commented on Varsha2001/Task1.html
> +<h2>-:List:-</h2>
This looks good however, you can remove this code as it is not required in task.

2023-04-24 14:25 UTC, PradyumnaKrishna commented
I would also suggest you to push your code to branch `patch-1` and reopen #3 as it was your first Pull Request. Closing this one and merging #3.

2023-05-02 08:40 UTC, PradyumnaKrishna commented
Closing (duplicate of #3)

2023-05-02 08:40 UTC, closed without merging