Completed Tasks Upto 6
CC-BHU/web-development pull request #73
Opened 2023-05-17 23:07 UTC by Rajkumar562

Leave any suggestions to make any changes.

2023-05-18 02:02 UTC, PradyumnaKrishna requested changes

2023-05-18 02:02 UTC, PradyumnaKrishna commented on Rajkumar562/style.css
We won't need this, Use style in document.

2023-05-18 19:10 UTC, Rajkumar562 commented on Rajkumar562/style.css
Updated the same as requested. Please look into it.

2023-05-19 04:46 UTC, PradyumnaKrishna requested changes
Please make the following changes.

2023-05-19 04:46 UTC, PradyumnaKrishna commented on Rajkumar562/task2.html
> +<div class="text">Welcome to the Retro City, looks mesmerising isn't it?</div>
This text-box isn't relative to the image, try adding all this to a parent div that have `position: absolute;`.

2023-05-19 04:46 UTC, PradyumnaKrishna commented on Rajkumar562/task4.html
> +    <style>
I have provided a CSS to style this task.

2023-05-19 16:40 UTC, Rajkumar562 commented
Made the requisite changes.

2023-05-19 17:27 UTC, PradyumnaKrishna approved these changes
Amazing Work @Rajkumar562!

2023-05-19 17:28 UTC, PradyumnaKrishna commented
After syncing you fork to CC-BHU/main, discard all the commits.
Use command
```bash
git reset --hard origin/main
```
It will fix your local git repo.

2023-05-19 17:29 UTC, merged